version: '3'
services:
  node-app:
    build:
      context: .
      args:
        NODE_ENV: production
    environment:
      - PORT=3000
    ports:
      - 3000:3000
    volumes:
      - ./:/app
      - /app/node_modules
