version: '3'
services:
  node-app:
    build: .
    environment:
      - PORT=3000
      - DB_HOST=db
      - DB_USER=oscar
      - DB_NAME=oscar
      - DB_PASS=mypassword
      - DB_PORT=5432
      - REDIS_URL=redis
      - REDIS_PORT=6379
    ports:
      - 3000:3000
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - db
      - redis
    networks:
      - app-network

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=oscar
      - POSTGRES_USER=oscar
      - POSTGRES_PASSWORD=mypassword
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./mock_data.sql:/docker-entrypoint-initdb.d/mock_data.sql
    ports:
      - '5432:5432'
    networks:
      - app-network

  redis:
    image: redis:latest
    networks:
      - app-network
    ports:
      - 6379:6379

networks:
  app-network:

volumes:
  postgres-data:
